# Generated by Django 5.2.3 on 2025-06-17 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('morning_start_time', models.TimeField(help_text='Morning session start time, e.g., 08:00')),
                ('morning_end_time', models.TimeField(help_text='Morning session end time, e.g., 12:00')),
                ('afternoon_start_time', models.TimeField(help_text='Afternoon session start time, e.g., 14:00')),
                ('afternoon_end_time', models.TimeField(help_text='Afternoon session end time, e.g., 18:00')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(help_text="e.g., New Year's Day", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('centers', models.ManyToManyField(help_text='Centers where this doctor works', related_name='doctors', to='scheduling.attentioncenter')),
                ('user', models.OneToOneField(help_text='Link to a user account marked as staff/doctor', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('VACCINATION', 'Vaccination'), ('LAB_EXAM', 'Lab Exam'), ('CERTIFICATE', 'Certificate')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Default duration in minutes for an appointment of this service')),
                ('specific_start_time', models.TimeField(blank=True, help_text='Optional: Specific start time for this service, e.g., 07:00 for lab exams', null=True)),
                ('specific_end_time', models.TimeField(blank=True, help_text='Optional: Specific end time for this service, e.g., 10:00 for lab exams', null=True)),
                ('requires_doctor_assignment', models.BooleanField(default=False, help_text='Is a doctor required for this service type? (e.g., Consultations)')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='scheduling.attentioncenter')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week for this availability slot')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabilities', to='scheduling.attentioncenter')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='scheduling.doctor')),
            ],
            options={
                'verbose_name_plural': 'Doctor Availabilities',
                'unique_together': {('doctor', 'center', 'day_of_week', 'start_time')},
            },
        ),
    ]
