# Generated by Django 5.2.3 on 2025-06-17 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0002_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Optional: Number of days the certificate is valid for.', null=True)),
                ('issuance_service', models.ForeignKey(blank=True, help_text='The service that must be booked to obtain this certificate.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.service')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_description', models.CharField(max_length=500)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='certificates.certificatetype')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_identifier', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('qr_code_data', models.TextField(blank=True, help_text='Data to be embedded in the QR code, e.g., a verification URL.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes by issuing staff or doctor.')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='scheduling.appointment')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
