# Generated by Django 5.2.3 on 2025-06-17 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcertificate',
            name='certificate_identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the certificate (UUID)', unique=True),
        ),
        migrations.AlterField(
            model_name='patientcertificate',
            name='qr_code_data',
            field=models.URLField(blank=True, help_text='Full verification URL to be embedded in the QR code.', max_length=500),
        ),
    ]
