# Generated by Django 5.2.3 on 2025-06-17 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0002_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('result_type', models.CharField(choices=[('NUMERIC', 'Numeric'), ('LIST', 'List-based'), ('TEXT', 'Descriptive Text')], max_length=10)),
                ('service_link', models.ForeignKey(blank=True, help_text='The lab service that must be booked for this test definition.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.service')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_value', models.CharField(help_text='e.g., Positive, Negative, A+, Clear', max_length=100)),
                ('is_normal_value', models.BooleanField(default=True, help_text='Is this list item considered a normal finding?')),
                ('test_definition', models.ForeignKey(limit_choices_to={'result_type': 'LIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='labresults.labtestdefinition')),
            ],
            options={
                'unique_together': {('test_definition', 'item_value')},
            },
        ),
        migrations.CreateModel(
            name='LabTestNumericRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(help_text='e.g., Hemoglobin, Glucose', max_length=100)),
                ('unit', models.CharField(blank=True, help_text='e.g., g/dL, mg/dL', max_length=50)),
                ('lower_bound_normal', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('upper_bound_normal', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('notes_for_range', models.CharField(blank=True, help_text='Optional notes, e.g., Varies with age/gender', max_length=255)),
                ('test_definition', models.ForeignKey(limit_choices_to={'result_type': 'NUMERIC'}, on_delete=django.db.models.deletion.CASCADE, related_name='numeric_ranges', to='labresults.labtestdefinition')),
            ],
            options={
                'unique_together': {('test_definition', 'parameter_name')},
            },
        ),
        migrations.CreateModel(
            name='PatientLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_datetime', models.DateTimeField(blank=True, help_text='Date and time of sample collection.', null=True)),
                ('reported_datetime', models.DateTimeField(blank=True, help_text='Date and time result was reported.', null=True)),
                ('notes_overall', models.TextField(blank=True, help_text='Overall comments on this lab test instance by lab staff.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
                ('test_definition', models.ForeignKey(help_text='The type of lab test performed.', on_delete=django.db.models.deletion.PROTECT, to='labresults.labtestdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PatientLabResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('parameter_name_display', models.CharField(help_text='The name of the parameter being reported, e.g., Hemoglobin, Color, Microscopic Examination', max_length=100)),
                ('is_abnormal', models.BooleanField(default=False, help_text='Automatically determined or manually set if abnormal.')),
                ('value_notes', models.TextField(blank=True, help_text='Notes specific to this particular value/finding.')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='labresults.patientlabresult')),
                ('list_value_selected', models.ForeignKey(blank=True, help_text='Links to the selected list item.', null=True, on_delete=django.db.models.deletion.PROTECT, to='labresults.labtestlistitem')),
                ('numeric_range_item_tested', models.ForeignKey(blank=True, help_text='Links to the specific numeric parameter definition.', null=True, on_delete=django.db.models.deletion.PROTECT, to='labresults.labtestnumericrange')),
            ],
        ),
    ]
